"""Generate verilog/rtl/openframe_gpio.v from a validated openframe spec."""

from typing import List

from chipfoundry_cli.openframe.spec import MODES, NUM_PADS, OVERRIDES, PAD_PORTS, OpenframeSpec, Pad

GPIO_RTL_REL = "verilog/rtl/openframe_gpio.v"
MODULE_NAME = "openframe_gpio"


def _range(width) -> str:
    return f"[{width - 1}:0]" if width is not None else ""


def _signal_ref(name: str, width, bit: int) -> str:
    return f"{name}[{bit}]" if width is not None else name


def _pad_label(spec: OpenframeSpec, pad: Pad) -> str:
    if pad.unused:
        return "(unused)"
    if pad.signal is None:
        return "(no signal)"
    sig = next(s for s in spec.signals if s.name == pad.signal)
    return f"{pad.signal}[{pad.bit}]" if sig.width is not None else pad.signal


def generate_gpio_rtl(spec: OpenframeSpec) -> str:
    lines: List[str] = []
    w = lines.append

    w("// " + "-" * 77)
    w(f"// {MODULE_NAME}")
    w("//")
    w("// GENERATED FILE - DO NOT EDIT.")
    w("// Generated by `cf openframe generate` from the")
    w("// project.openframe block in .cf/project.json. Edit the spec with")
    w("// `cf gpio-config` or `cf openframe import`, then regenerate.")
    w(f"// spec-sha256: {spec.sha256}")
    if any(p.overrides for p in spec.pads):
        w("// Uses CF_gpio_config pad overrides: requires CF_gpio_config v1.2.0 or later.")
    w("//")
    w("// Pad map:")
    for pad in spec.pads:
        w(f"//   pad {pad.pad:2d}  {pad.mode:<8s}  {_pad_label(spec, pad)}")
    w("// " + "-" * 77)
    w("")
    w("`default_nettype none")
    w("")
    w("// io_in is left open on pads that have no input signal.")
    w("/* verilator lint_off PINCONNECTEMPTY */")
    w(f"module {MODULE_NAME} (")

    port_lines = []
    if spec.signals:
        port_lines.append("    // User design ports")
        for sig in spec.signals:
            for port, direction in sig.ports():
                rng = _range(sig.width)
                port_lines.append(f"    {direction:<6s} wire {rng:<7s} {port},")
        port_lines.append("")
    port_lines.append("    // Openframe pad interface: connect to the openframe_project_wrapper ports of the same name")
    pad_rng = f"[{NUM_PADS - 1}:0]"
    for i, (port, direction) in enumerate(PAD_PORTS):
        sep = "," if i < len(PAD_PORTS) - 1 else ""
        port_lines.append(f"    {direction:<6s} wire {pad_rng:<7s} {port}{sep}")
    lines.extend(port_lines)
    w(");")

    for pad in spec.pads:
        lines.extend(_instance(spec, pad))

    w("")
    w(f"endmodule // {MODULE_NAME}")
    w("/* verilator lint_on PINCONNECTEMPTY */")
    w("")
    w("`default_nettype wire")
    return "\n".join(lines) + "\n"


def _instance(spec: OpenframeSpec, pad: Pad) -> List[str]:
    n = pad.pad
    # Unused user inputs are tied to the pad's loopback constants (ignored by CF_gpio_config in these modes).
    io_in = ""
    io_out = f"gpio_loopback_zero[{n}]"
    io_oeb = f"gpio_loopback_one[{n}]"
    if pad.signal is not None:
        sig = next(s for s in spec.signals if s.name == pad.signal)
        bit = pad.bit if pad.bit is not None else 0
        if sig.direction == "in":
            io_in = _signal_ref(sig.name, sig.width, bit)
        elif sig.direction == "out":
            io_out = _signal_ref(sig.name, sig.width, bit)
        else:
            io_in = _signal_ref(f"{sig.name}_in", sig.width, bit)
            io_out = _signal_ref(f"{sig.name}_out", sig.width, bit)
            io_oeb = _signal_ref(f"{sig.name}_oeb", sig.width, bit)

    params = [f".MODE(3'd{MODES[pad.mode]})"]
    for key, param in OVERRIDES.items():
        if key in pad.overrides:
            params.append(f".{param}(1'b{pad.overrides[key]})")

    out = ["", f"    // pad {n}: {pad.mode} {_pad_label(spec, pad)}"]
    out.append("    CF_gpio_config #(")
    out.extend(f"        {p}{',' if i < len(params) - 1 else ''}" for i, p in enumerate(params))
    out.append(f"    ) gpio_cfg_{n:02d} (")
    conns = [
        ("io_out", io_out),
        ("io_in", io_in),
        ("io_oeb", io_oeb),
        ("gpio_zero", f"gpio_loopback_zero[{n}]"),
        ("gpio_one", f"gpio_loopback_one[{n}]"),
        ("gpio_in", f"gpio_in[{n}]"),
        ("gpio_dm", f"{{gpio_dm2[{n}], gpio_dm1[{n}], gpio_dm0[{n}]}}"),
        ("gpio_inp_dis", f"gpio_inp_dis[{n}]"),
        ("gpio_oeb_out", f"gpio_oeb[{n}]"),
        ("gpio_out_val", f"gpio_out[{n}]"),
        ("gpio_analog_en", f"gpio_analog_en[{n}]"),
        ("gpio_analog_sel", f"gpio_analog_sel[{n}]"),
        ("gpio_analog_pol", f"gpio_analog_pol[{n}]"),
        ("gpio_ib_mode_sel", f"gpio_ib_mode_sel[{n}]"),
        ("gpio_vtrip_sel", f"gpio_vtrip_sel[{n}]"),
        ("gpio_slow_sel", f"gpio_slow_sel[{n}]"),
        ("gpio_holdover", f"gpio_holdover[{n}]"),
    ]
    for i, (pin, net) in enumerate(conns):
        sep = "," if i < len(conns) - 1 else ""
        out.append(f"        .{pin:<16s} ({net}){sep}")
    out.append("    );")
    return out
