"""Generate openlane/openframe_project_wrapper/power.json (LibreLane 3.x PDN variables)."""

import json
from typing import Any, Dict

from chipfoundry_cli.openframe.spec import POWER_DOMAINS, OpenframeSpec

POWER_JSON_REL = "openlane/openframe_project_wrapper/power.json"


def power_config(spec: OpenframeSpec) -> Dict[str, Any]:
    """LibreLane config fragment for the wrapper PDN.

    ``PDN_MACRO_CONNECTIONS`` entries follow LibreLane's
    ``<instance_regex> <vdd_net> <gnd_net> <vdd_pin> <gnd_pin>`` format.
    """
    return {
        "//": "Generated by `cf openframe generate` from project.openframe.power in .cf/project.json. Do not edit.",
        "// spec-sha256": spec.sha256,
        "VDD_NETS": list(spec.domains),
        "GND_NETS": [POWER_DOMAINS[d] for d in spec.domains],
        "PDN_MACRO_CONNECTIONS": [
            f"{m.instance} {m.domain} {m.gnd_net} {m.vdd_pin} {m.gnd_pin}" for m in spec.macros
        ],
    }


def generate_power_json(spec: OpenframeSpec) -> str:
    return json.dumps(power_config(spec), indent=4) + "\n"
